---
version: '3'

services:

  web:
    image: nginx:1.20-alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./site/:/var/www/html/
      - ./conf/website.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginxphp

  php-fpm:
    image: php:7.4-fpm-alpine
    container_name: php-fpm
    volumes:
      - ./site/:/var/www/html/
    expose:
      - 9000
    networks:
      - nginxphp

networks:
  nginxphp: 
